# Site settings
title: Steven Wu
description: Steven Wu's Personal Website
# baseurl: "/home" # the subpath of your site, e.g. /blog
# url: "stevenwu2019.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Steven Wu
user_description: Hello Internet! I'm a second-year undergrad in the School of Computer Science at Carnegie Mellon University in Pittsburgh, PA. My interests lie in pursuing advancements within the fields of robotics and autonomy, though I'm always open to experimenting with new ideas. I'm passionate about exploring technology's impact on human culture and society, perfecting the art of storytelling, lining up golden shots in foosball, and cheering on the Dallas Mavericks no matter the odds. 
user_title: Computer Science @ CMU
email: stevenwu@andrew.cmu.edu
linkedin_username:  stevenwu2019
github_username:  stevenwu2019

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
